[phases.setup]
nixPkgs = ["nodejs_22", "pnpm-9_x", "openssl", "awscli2", "jq"]

[phases.install]
cmds = [
  "npm install -g corepack@0.24.1 && corepack enable",
  "pnpm i --frozen-lockfile"
]

[phases.build]
cmds = ["npx turbo run build"]

[start]
cmd = "./start.sh"
