MailLogger.mailhost=localhost
MailLogger.from=pace-dev@efi.com
MailLogger.failure.notify=true
MailLogger.failure.to=pace-dev@efi.com
MailLogger.success.notify=false
MailLogger.success.to=pace-dev@efi.com

